marklion/mobile_trade

- mt_gui/pages/Home.vue
> 主页统计表需要增加收缩加长功能

- mt_gui/pages/Field.vue
> 现场管理界面，新增正在泄压信息提示

- mt_gui/pages/Driver.vue
- mt_gui/pages/OrderList.vue
> 安检页面图片放大查看

- mt_gui/pages/Stuff.vue
> ZYZL-395 #add exam switch in stuff config page

- api/db_opt.js
- api/index.js
- api/legacy_api.js
- api/lib/field_lib.js
- api/lib/plan_lib.js
- api/lib/sc_lib.js
- api/lib/util_lib.js
- api/module/common.js
- api/module/customer_module.js
- api/module/global_module.js
- api/module/sale_management_module.js
- api/module/supplier_module.js
- api/plugin/hnmhg.js
- automation/stuff/plan_standard.robot
- automation/stuff/stuff_opt.resource
- deploy.sh
- mt_gui/pages/Myself.vue
- script/timer.sh
> ZYZL-401 #add auto uncheck in feature

- api/module/global_module.js
- automation/exam/exam.resource
- mt_gui/pages.json
- mt_gui/pages/Driver.vue
- mt_gui/pages/Ticket.vue
- mt_gui/subPage1/Exam.vue
> ZYZL-396--

- api/db_opt.js
- api/module/global_module.js
- mt_gui/pages/Admin.vue
- mt_gui/pages/Home.vue
这是没有logo的界面
这是有logo的界面
这是设置logo的界面
> ZYZL-316 # add company logo

- mt_gui/subPage1/ExamConfig.vue
> ZYZL-394 #add link question 2 paper feature

- mt_gui/pages/RoleConfig.vue
> ZYZL-410--角色配置UI分块布局

- mt_gui/pages/Home.vue
- mt_gui/pages/Stuff.vue
> ZYZL-403--fix物料管理Stuff中的开关点击触发问题

- api/api_param_result_define.js
- api/db_opt.js
- api/lib/plan_lib.js
- api/module/sale_management_module.js
- api/module/stuff_module.js
- mt_gui/pages/OrderList.vue
- mt_gui/pages/Stuff.vue
> ZYZL-413 #add fapiao mark

- api/module/sale_management_module.js
- mt_gui/pages/OrderList.vue
> ZYZL-376--客户余额可视校验(无权限不返回余额信息)

- extern/scan_print/index.js
- extern/scan_print/package.json
- extern/yangbang_led/Obasic_types.h
- extern/yangbang_led/bx_dual_sdk.h
- extern/yangbang_led/bx_sdk_dual.h
- extern/yangbang_led/index.js
- extern/yangbang_led/libbx_sdkDual.so
- extern/yangbang_led/main.cpp
- extern/yangbang_led/package-lock.json
- extern/yangbang_led/package.json
- sonar-project.properties
> ZYZL-415--

- api/lib/plan_lib.js
- api/module/buy_management_module.js
- api/module/common.js
- api/module/sale_management_module.js
- automation/stuff/stuff_curd.robot
- automation/stuff/stuff_opt.resource
- mt_gui/pages/Contract.vue
> ZYZL-419 #add contract update feature

- mt_gui/pages/OrderCreate.vue
> Zyzl 404  下单界面需要校验输入信息

- mt_gui/pages/Home.vue
- mt_gui/pages/OrderCreate.vue
- mt_gui/pages/OrderList.vue
- mt_gui/pages/Stuff.vue
> ZYZL-416 #make space more sence

- api/db_opt.js
- api/lib/plan_lib.js
- api/module/sale_management_module.js
- mt_gui/pages/Stuff.vue
> ZYZL-420 #add price profile

- mt_gui/components/ListShow.vue
> ZYZL-409--点完叉以后直接取消搜索框

- mt_gui/pages/OrderList.vue
> ZYZL-417--订单页加载优化

- mt_gui/components/DevOpt.vue
- mt_gui/pages/Field.vue
> ZYZL-353--设备管理开关门操作完成后自动刷新最新数据

- mt_gui/main.js
- mt_gui/pages/Contract.vue
- mt_gui/pages/OrderList.vue
> ZYZL-422--订单页面和合同页面查看资质时需要增加一个下载图片的按钮

- api/api_param_result_define.js
- api/lib/plan_lib.js
- mt_gui/pages/OrderList.vue
> ZYZL-387--计划重复时要增加提示信息

- api/api_param_result_define.js
- api/db_opt.js
- api/module/global_module.js
- mt_gui/pages/Admin.vue
- mt_gui/pages/Field.vue
> ZYZL-424--基于公司添加是否支持泄压配置选项

- api/module/sale_management_module.js
> ZYZL-414--合同删除重新创建时订单详情打开有问题

- mt_gui/subPage1/Stuff.vue
> ZYZL-431--加上星号

- mt_gui/pages/Contract.vue
> ZYZL-423--合同管理页面查看资质有问题

- mt_gui/pages/Driver.vue
- mt_gui/pages/OrderList.vue
> ZYZL-430--安检照片放大后的退出按钮点不到

- mt_gui/subPage1/OrderCreate.vue
> ZYZL-432--下单界面添加车辆UI调整

- api/module/global_module.js
- mt_gui/components/NoticeBar.vue
- mt_gui/pages/Home.vue
- mt_gui/pages/Myself.vue
- mt_gui/subPage1/SysNotice.vue
> ZYZL-438--增加系统维护通知

- api/lib/plan_lib.js
- mt_gui/pages/OrderList.vue
> ZYZL-428 # add one more upate limit

- .gitignore
- api/lib/plan_lib.js
> ZYZL-439 #add comment into export table

- api/api_param_result_define.js
- api/db_opt.js
- api/lib/bidding_lib.js
- api/module/customer_module.js
- automation/bidding/bidding_config.robot
- automation/bidding/bidding_exception.robot
- automation/bidding/bidding_opt.resource
- mt_gui/components/BidDetail.vue
- mt_gui/pages/BiddingJoin.vue
> ZYZL-445 #add price confirm feature after bidding finished

- api/db_opt.js
- api/lib/plan_lib.js
- api/module/common.js
- api/module/customer_module.js
- api/module/stuff_module.js
- api/module/supplier_module.js
- automation/black_list/black_list.resource
- automation/black_list/black_list.robot
- automation/stuff/stuff_opt.resource
- mt_gui/App.vue
- mt_gui/pages/OrderList.vue
- mt_gui/subPage1/BlackList.vue
- mt_gui/subPage1/Stuff.vue
> ZYZL-436--增加黑名单功能

- api/module/buy_management_module.js
- api/module/common.js
- api/module/sale_management_module.js
- mt_gui/pages/OrderList.vue
> ZYZL-433--订单页添加合同信息展示

- api/db_opt.js
- api/lib/plan_lib.js
- api/module/global_module.js
- api/module/stuff_module.js
- mt_gui/subPage1/CompanyAttach.vue
- mt_gui/subPage1/Stuff.vue
> ZYZL-442--增加资质证书强制检查选项

- api/module/global_module.js
- mt_gui/pages/Export.vue
> ZYZL-434--导出页面增加批量导出磅单功能

- api/db_opt.js
- api/lib/plan_lib.js
- api/module/customer_module.js
- api/module/stuff_module.js
- automation/stuff/plan_exception.robot
- automation/stuff/plan_standard.robot
- automation/stuff/stuff_opt.resource
- mt_gui/src/subPage1/Stuff.vue
> ZYZL-451  

- api/db_opt.js
- api/lib/fc_lib.js
- api/module/rbac_module.js
- api/module/safe_check_module.js
- automation/database.resource
- automation/safe_check/sc_config.robot
- automation/safe_check/sc_opt.resource
- mt_gui/src/pages/ScConfig.vue
> ZYZL-448 add field check table

- api/api_param_result_define.js
- api/db_opt.js
- api/lib/sc_lib.js
- api/module/global_module.js
- api/module/safe_check_module.js
- mt_gui/src/pages/Export.vue
- mt_gui/src/pages/ScConfig.vue
> ZYZL-447--安检项目增加是否加入登记表导出的选项

- mt_gui/src/subPage1/OrderCreate.vue
> ZYZL-454--创建计划时的导入表新增一列备注

- api/db_opt.js
- api/lib/bidding_lib.js
- api/lib/fc_lib.js
- api/lib/plan_lib.js
- api/lib/util_lib.js
- api/module/global_module.js
- api/module/safe_check_module.js
- automation/database.resource
- automation/safe_check/sc_config.robot
- automation/safe_check/sc_opt.resource
- mt_gui/src/pages.json
- mt_gui/src/pages/OrderList.vue
- mt_gui/src/subPage1/FcExecute.vue
> ZYZL-449 add fc execute page

- .gitignore
- api/db_opt.js
- api/lib/fc_lib.js
- api/module/safe_check_module.js
- api/package-lock.json
- api/package.json
- mt_gui/src/pages/Export.vue
- mt_gui/src/subPage1/ScConfig.vue
> ZYZL-450 #add export  fc feature

- api/api_param_result_define.js
- api/db_opt.js
- api/lib/plan_lib.js
- api/module/scale_module.js
- api/module/stuff_module.js
- automation/stuff/plan_exception.robot
- mt_gui/src/components/Measurement.vue
- mt_gui/src/pages/OrderList.vue
- mt_gui/src/subPage1/Field.vue
- mt_gui/src/subPage1/Stuff.vue
> ZYZL-453--修改手动上传装车数据的形式

- mt_gui/src/pages/Export.vue
> ZYZL-460--安检登记表，下载问题

- mt_pc/src/router/index.js
- mt_pc/src/store/modules/app.js
- mt_pc/src/views/stuff/BlackList.vue
- mt_pc/src/views/stuff/GlobalStrategy.vue
- mt_pc/src/views/stuff/StuffConfig.vue
> ZYZL-457-PC-在PC端增加物料相关的页面

- mt_gui/src/components/Measurement.vue
> ZYZL-468--wxfile-手动计量的上传图片界面不要放置上传按钮了

- mt_pc/src/components/PageSelect.vue
- mt_pc/src/components/SelectSearch.vue
- mt_pc/src/router/index.js
- mt_pc/src/views/bidding/BiddingConfig.vue
- mt_pc/src/views/bidding/BiddingJoin.vue
> ZYZL-462-PC-PC端增加竞价界面

- api/lib/sc_lib.js
> ZYZL-474--安检项配置改变后需要将该项对应的安检内容置为不通过

- api/api_param_result_define.js
- api/db_opt.js
- api/module/scale_module.js
- api/module/stuff_module.js
- mt_gui/src/components/Measurement.vue
- mt_gui/src/subPage1/Stuff.vue
> ZYZL-475--手动计量的磅单需要显示出两次计量的时间和磅单号

- mt_gui/src/subPage1/Field.vue
> ZYZL-486--在现场管理的排队车辆界面里放置一个检查键

- .github/workflows/release.yml
- .gitignore
- Makefile
- README.md
- api/Makefile
- api/legacy_api.js
- api/lib/wx_api_util.js
- api/module/global_module.js
- conf/Makefile
- conf/nginx.conf
- deploy.sh
- lag_rpc/Makefile
- mt_gui/Makefile
- mt_gui/package.json
- mt_gui/src/main.js
- mt_gui/src/manifest.json
- mt_gui/src/pages/Ticket.vue
- mt_gui/vue.config.js
- mt_pc/Makefile
- mt_pc/package.json
- mt_pc/src/main.js
- mt_pc/src/router/index.js
- mt_pc/src/views/login.vue
- mt_pc/vue.config.js
- zczh/Makefile
- zczh/api/Makefile
- zczh/deploy.sh
1. 使用参数构建本地包，可以访问手机网页和电脑网页 pass
2. 基于IDE调试手机网页和电脑网页，请求都到本地，文件到默认云 pass
3. 两种环境调用/pa_rest/vehicle_detail有附件 pass
4. 两种环境调用下载磅单 pass
5. 两种环境的磅单二维码 pass
6. 两个环境的PC网页帮助页面和API页面 pass
7. 两种环境上传和访问附件 pass
> Zyzl 485  id 

- .vscode/settings.json
- extern/modbus_scale_total/CMakeLists.txt
- extern/modbus_scale_total/main.c
新增一个独立运行的程序，用于提供基于串口的重量获取服务。达到的效果是：
1. 让一个主机表现为一个拥有串口的仪表
2. 该仪表支持两个modbus指令
3. modbus中的数据来源于数据库文件
> ZYZL-489 Add modbus_scale_total project

- api/Makefile
- mt_pc/src/components/FcExecute.vue
- mt_pc/src/components/OrderDetail.vue
- mt_pc/src/components/OrderVerify.vue
- mt_pc/src/components/PageContent.vue
- mt_pc/src/components/UploadForm.vue
> Zyzl 461 pc 

- mt_pc/src/views/stuff/StuffConfig.vue
> ZYZL-470 #put history into page content

- mt_pc/src/views/stuff/StuffConfig.vue
> Zyzl 471 pc调价界面中的是否影响计划应该根据配置自动打开

- mt_gui/src/pages/OrderList.vue
- mt_gui/src/subPage1/Contract.vue
- mt_pc/src/components/ContractShowTable.vue
- mt_pc/src/components/OrderDetail.vue
- mt_pc/src/components/SelectSearch.vue
- mt_pc/src/router/index.js
- mt_pc/src/views/contract/ContractBought.vue
- mt_pc/src/views/contract/ContractBuy.vue
- mt_pc/src/views/contract/ContractSale.vue
- mt_pc/src/views/contract/ContractSold.vue
> ZYZL-496 #add contract management page on PC

- mt_pc/src/components/List4Stuff.vue
- mt_pc/src/main.js
- mt_pc/src/router/index.js
- mt_pc/src/views/bidding/BiddingConfig.vue
- mt_pc/src/views/sc/FieldCheck.vue
- mt_pc/src/views/sc/LicenseCheck.vue
> Zyzl 497 pc端增加安检配置界面

- mt_pc/src/components/ExportDate.vue
- mt_pc/src/main.js
- mt_pc/src/router/index.js
- mt_pc/src/utils/request.js
- mt_pc/src/utils/sendReq.js
- mt_pc/src/views/export/ExportExecute.vue
- mt_pc/src/views/export/ExportRecord.vue
- mt_pc/src/views/sc/FieldCheck.vue
> ZYZL-501 #add export pages on PC

- mt_pc/src/router/index.js
- mt_pc/src/views/Rbac.vue
> ZYZL-502 add rbac

- api/api_param_result_define.js
- api/db_opt.js
- api/index.js
- api/lib/cash_lib.js
- api/lib/plan_lib.js
- api/module/cash_module.js
- api/module/stuff_module.js
- api/module/u8c_module.js
- mt_pc/src/router/index.js
- mt_pc/src/views/stuff/StuffConfig.vue
- mt_pc/src/views/u8c.vue
> Zyzl 494 实现用友u8 c对接开发

- .devcontainer/Dockerfile
- api/lib/plan_lib.js
- api/module/sale_management_module.js
- api/package.json
- mt_gui/src/pages/Home.vue
- mt_pc/package.json
- mt_pc/src/components/Charts.vue
- mt_pc/src/router/index.js
- mt_pc/src/utils/request.js
- mt_pc/src/views/dashboard.vue
- mt_pc/src/views/order/OrderCreate.vue
> Zyzl 488 pc 实现pc端页面的主页 内容和手机端相同

- api/module/global_module.js
- mt_gui/src/subPage1/BiddingJoin.vue
> ZYZL-507 #change bidding verify code

- mt_pc/src/views/stuff/StuffConfig.vue
> ZYZL-511 参考手机端业务添加一个switch开关，并且添加一个方法。

- api/api_param_result_define.js
- api/db_opt.js
- api/lib/cash_lib.js
- api/lib/plan_lib.js
- api/lib/util_lib.js
- api/module/global_module.js
- api/module/sale_management_module.js
- api/module/stuff_module.js
- api/module/u8c_module.js
- mt_gui/src/pages/OrderList.vue
- mt_gui/src/pages/Ticket.vue
- mt_pc/src/components/OrderDetail.vue
- mt_pc/src/components/OrderShowTable.vue
- mt_pc/src/views/stuff/GlobalStrategy.vue
- mt_pc/src/views/u8c.vue
> ZYZL-513 add delegate feature for sale

- api/db_opt.js
- api/module/cash_module.js
- api/module/sale_management_module.js
- api/module/stuff_module.js
- automation/rbac/rbac_curd.resource
- automation/stuff/plan_exception.robot
- automation/stuff/stuff_opt.resource
- mt_gui/src/pages/OrderList.vue
- mt_gui/src/subPage1/Stuff.vue
- mt_pc/src/components/OrderDetail.vue
- mt_pc/src/components/OrderShowTable.vue
- mt_pc/src/views/stuff/GlobalStrategy.vue
> ZYZL-515 add pay verify switch feature

- api/lib/rbac_lib.js
- api/module/rbac_module.js
- mt_pc/src/components/SelectSearch.vue
- mt_pc/src/views/Rbac.vue
- mt_pc/src/views/login.vue
> Zyzl 509 权限配置时的人员添加改为选择

- api/api_param_result_define.js
- api/db_opt.js
- api/lib/plan_lib.js
- mt_gui/src/pages/OrderList.vue
- mt_pc/src/components/OrderDetail.vue
- mt_pc/src/components/OrderShowTable.vue
ZYZL-516-手机和PC界面-订单列表和订单详细页面都要添加该单还差多少钱 
1.修复订单页面endDate脏数据的问题
2.添加arrears 显示欠额数
> Zyzl 516 手机和pc界面 订单列表和订单详细页面都要添加该单还差多少钱

- api/api_param_result_define.js
- api/db_opt.js
- api/lib/plan_lib.js
- api/lib/util_lib.js
- api/module/global_module.js
- api/module/scale_module.js
- api/module/stuff_module.js
- automation/stuff/plan_standard.robot
- automation/stuff/stuff_curd.robot
- automation/stuff/stuff_opt.resource
- mt_gui/src/components/Measurement.vue
- mt_gui/src/pages/Ticket.vue
- mt_pc/src/views/stuff/StuffConfig.vue
> ZYZL-527 # add structured input method for manual measurement

- api/api_param_result_define.js
- api/db_opt.js
- api/lib/util_lib.js
- api/module/global_module.js
- api/module/stuff_module.js
- mt_gui/src/pages/Ticket.vue
- mt_pc/src/views/stuff/GlobalStrategy.vue
Zyzl 526 磅单内容修改添加全局配置label替换信息
> Zyzl 526 磅单内容修改

- api/db_opt.js
- api/lib/plan_lib.js
- api/module/scale_module.js
- api/module/stuff_module.js
- mt_gui/src/subPage1/Field.vue
- mt_pc/src/views/field/Queue.vue
- mt_pc/src/views/stuff/StuffConfig.vue
> ZYZL-528 # add option for month add base

- api/db_opt.js
- api/lib/plan_lib.js
- api/module/global_module.js
- api/module/scale_module.js
- api/module/stuff_module.js
- mt_gui/src/pages/OrderList.vue
- mt_gui/src/subPage1/Field.vue
- mt_gui/src/subPage1/ScExecute.vue
- mt_pc/src/views/stuff/GlobalStrategy.vue
> ZYZL-532 # add switch for sc check entry

- api/lib/plan_lib.js
- mt_pc/src/components/ExportDate.vue
- mt_pc/src/views/export/ExportExecute.vue
> ZYZL-533 #add delegate when export and finish switch on export card

- mt_gui/src/subPage1/FcExecute.vue
1.添加“一键检查”按钮
2.将所有的swith开关设置为开启状态
3.提交检查
> ZYZL-531-在现场检查界面-基于表增加一键检查通过按键

- api/db_opt.js
- api/lib/plan_lib.js
- api/module/global_module.js
- api/module/stuff_module.js
- mt_pc/src/views/stuff/GlobalStrategy.vue
> ZYZL-537 add hard mode for buy

- .vscode/settings.json
- automation/stuff/plan_standard.robot
- automation/stuff/stuff_curd.robot
- automation/stuff/stuff_opt.resource
- automation/var.resource
> ZYZL-539-基于第二单位添加自动化测试

- api/api_param_result_define.js
- api/db_opt.js
- api/lib/cash_lib.js
- api/lib/plan_lib.js
- api/module/cash_module.js
- automation/stuff/stuff_curd.robot
- automation/stuff/stuff_opt.resource
- automation/stuff/subsidy.robot
- mt_pc/src/components/OrderDetail.vue
- mt_pc/src/router/index.js
- mt_pc/src/views/subsidy/DoSubsidy.vue
- mt_pc/src/views/subsidy/SubsidyConfig.vue
> ZYZL-520 #add subsidy feature

- api/api_param_result_define.js
- api/db_opt.js
- api/module/global_module.js
- api/module/stuff_module.js
- mt_gui/src/pages/Ticket.vue
- mt_pc/src/components/StampPic.vue
- mt_pc/src/views/field/SealPic.vue
- mt_pc/src/views/stuff/GlobalStrategy.vue
> ZYZL-540 #add stamp for delegate

- mt_pc/src/views/bidding/BiddingConfig.vue
> ZYZL-542 # add hidden price option in PC web

- mt_gui/src/pages/Ticket.vue
> ZYZL-545 #change ticket behavior when second unit is set

- api/lib/plan_lib.js
> ZYZL-546 #change statistics based on stuff to second unit

- zczh/service/cli/rule_cli.cpp
> ZYZL-544 #add oem config

- api/db_opt.js
- api/lib/wx_api_util.js
- api/module/global_module.js
- api/module/stuff_module.js
- automation/database.resource
- automation/wx_msg/wx_msg.robot
- mt_pc/src/views/stuff/GlobalStrategy.vue
ZYZL-529-在PC端全局配置增加一个开关-是否只推送消息给可写角色
> Zyzl 529 在pc端全局配置增加一个开关 是否只推送消息给可写角色

- api/api_param_result_define.js
- api/db_opt.js
- api/module/global_module.js
- api/module/stuff_module.js
- mt_gui/src/pages/Ticket.vue
- mt_gui/src/subPage1/Stuff.vue
- mt_pc/src/views/stuff/StuffConfig.vue
> ZYZL-547 # add decimal places for second unit

- api/lib/plan_lib.js
> ZYZL-548 #add second unit column in export table

- api/db_opt.js
- api/index.js
- api/lib/plan_lib.js
- api/lib/wx_api_util.js
- api/module/sale_management_module.js
- api/module/stuff_module.js
- automation/database.resource
- automation/rbac/rbac_curd.resource
- automation/stuff/plan_standard.robot
- automation/stuff/stuff_opt.resource
- mt_pc/src/views/stuff/StuffConfig.vue
- script/timer.sh
ZYZL-549 #add checkout delay feature
ZYZL-549 #adapt for statistic
ZYZL-549 #adapt for statistic
> ZYZL-549 #add delay checkout timer config

- automation/stuff/plan_standard.robot
- automation/stuff/stuff_opt.resource
> search_valid_plan_by_plate_id

- api/api_param_result_define.js
- api/db_opt.js
- api/module/global_module.js
- api/module/stuff_module.js
- mt_gui/src/pages/Ticket.vue
- mt_pc/src/views/stuff/GlobalStrategy.vue
1.全局添加下单公司替换文字项
2.全局添加运输公司替换文字项
> ZYZL-550-磅单字段自定义功能项增加

- api/lib/cash_lib.js
- api/module/u8c_module.js
- mt_pc/src/components/ExportDate.vue
- mt_pc/src/components/OrderShowTable.vue
- mt_pc/src/main.js
- mt_pc/src/views/subsidy/DoSubsidy.vue
- mt_pc/src/views/u8c.vue
ZYZL-551 add time range filter to U8C interface
ZYZL-551 add time range filter to U8C interface
> ZYZL-551 #add date filter to U8C interface

- api/api_param_result_define.js
- api/db_opt.js
- api/lib/plan_lib.js
- automation/stuff/plan_standard.robot
- mt_gui/src/pages/OrderList.vue
- mt_pc/src/components/OrderDetail.vue
- mt_pc/src/components/OrderShowTable.vue
> ZYZL-554-显示欠款第地方再增加一个几个车欠着款

- api/lib/wx_api_util.js
1.物料前加入时间 2025-06-16 LNG
2025-06-16 LNG
> ZYZL-557-在订单状态更新的微信消息中增加计划日期显示

- api/module/global_module.js
- mt_pc/src/views/export/ExportExecute.vue
> ZYZL-562-磅单导出界面增加客户选择

- api/db_opt.js
- api/lib/cash_lib.js
- api/module/cash_module.js
- automation/stuff/stuff_curd.robot
- automation/stuff/stuff_opt.resource
- automation/stuff/subsidy.robot
- mt_pc/src/views/subsidy/SubsidyConfig.vue
> ZYZL-563-补贴功能中-增加优惠额度的配置

- .github/workflows/release.yml
- api/db_opt.js
- api/module/global_module.js
- api/module/scale_module.js
- api/module/stuff_module.js
- mt_gui/Makefile
- mt_gui/src/pages/Export.vue
- mt_gui/src/subPage1/DevOpt.vue
- mt_gui/src/subPage1/Field.vue
- mt_gui/src/subPage1/OrderCreate.vue
- mt_pc/src/views/order/OrderCreate.vue
- mt_pc/src/views/stuff/GlobalStrategy.vue
1.增加全局配置，名字叫门禁权限关闭
2.上述配置打开的情况下，下图框中的按钮不显示
> ZYZL-567-现场门类型的设备增加可配置的操作选项

- mt_pc/src/views/stuff/GlobalStrategy.vue
> ZYZL-569-修改一个错别字-磅单

- api/module/cash_module.js
> ZYZL-572-磅单导出时给导出记录添加客户名

- api/lib/plan_lib.js
1.在所有导出结果尾行添加 合计 合计的内容有装卸总量 总价 和 共有多少单
代码层面没有找到分开的原因，看下换个环境测试是否达到预期效果
> ZYZL-573-订单明细导出的内容中添加合计行

- api/db_opt.js
- api/module/global_module.js
- api/module/scale_module.js
- api/module/stuff_module.js
- mt_gui/src/subPage1/DevOpt.vue
- mt_gui/src/subPage1/Field.vue
- mt_pc/src/views/stuff/GlobalStrategy.vue
1.全局添加一个开关
2.控制榜单类型的操作选项
3.后端添加对应的getset方法
4.前端添加对应的配置选项
> ZYZL-570-现场磅类型的设备增加可配置的操作选项

- api/db_opt.js
- api/lib/cash_lib.js
- api/module/cash_module.js
- automation/stuff/subsidy.robot
- mt_pc/src/views/subsidy/DoSubsidy.vue
> Zyzl 574 添加基于补贴记录的回退特性

- api/module/cash_module.js
> ZYZL-578-余额明细导出记录名有错

- api/lib/plan_lib.js
1.当m_xxx_time存在时，conditions里面的内容应该去掉
> ZYZL-584-导出订单明细时-若存在时间-则不过滤plan_time日期

- api/module/global_module.js
1.两个函数移出module.export 这个对象，定义到本文件内。
2.能够正常访问 /api/help
> ZYZL-585-移动函数定

- api/lib/fc_lib.js
> ZYZL-587-现场检查表的签名移动位置

- zczh/base/db_orm/zh_db_config.h
- zczh/base/idl/idl.thrift
- zczh/service/cli/rule_cli.cpp
- zczh/service/lib/config_management_imp.cpp
- zczh/service/lib/config_management_imp.h
- zczh/service/lib/device_management_imp.cpp
- zczh/service/lib/device_management_imp.h
```
root@dd837fd86681:~# zh_cli 
zczh> bdr
rbac
add_user api 18911992582 md5:698D51A19D8A121CE581499D7B701668
add_user admin 111 md5:698D51A19D8A121CE581499D7B701668
add_role admin 0
add_user_to_role 1 1
add_user_to_role 1 2
add_perm_to_role 1 1
add_perm_to_role 1 2
add_perm_to_role 1 3
add_perm_to_role 1 4
add_perm_to_role 1 5
add_perm_to_role 1 6
add_perm_to_role 1 7
add_perm_to_role 1 8
add_perm_to_role 1 9
add_perm_to_role 1 10
zczh
device
add_set 门 0
add_device '门后道闸' '-t 门' '1' '门' back_gate
add_device '门前道闸' '-t 门' '1' '门' front_gate
add_device '门后身份证' '-t 门' '1' '门' back_id_reader
add_device '门前身份证' '-t 门' '1' '门' front_id_reader
add_device '门后屏幕' '-t 门' '1' '门' back_led
add_device '门前屏幕' '-t 门' '1' '门' front_led
add_device '门后抓拍机' '-t 门' '1' '门' back_plate_cam
add_device '门前抓拍机' …
```
> ZYZL-597 add weight range to make weight scene
